In [1]:
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
import torch
import numpy as np
import time
from torchvision import datasets, transforms
from scipy.io import savemat, loadmat
from torch.utils.data import DataLoader, Subset, TensorDataset
from aeon.datasets import load_classification
from sklearn.preprocessing import StandardScaler, LabelEncoder
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from torch.utils.data import DataLoader, Subset
import matplotlib.pyplot as plt
from tqdm import tqdm


In [2]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
dataset_name = 'Epilepsy'

In [3]:
X_train, y_train, metadata = load_classification(dataset_name, return_metadata=True, split='train')
X_test, y_test = load_classification(dataset_name, split='test')
if X_train.shape[0] < 200:
    if X_test.shape[0] >= 200:
        train_size = int((X_train.shape[0] + X_test.shape[0]) * 1/4)
        x, y = load_classification(dataset_name)
        X_train, y_train = x[:train_size, :], y[:train_size]
        X_test, y_test = x[train_size:, :], y[train_size:]

In [4]:
input_channels = 1
if X_train.ndim == 3:
    input_channels = X_train.shape[1]
seq_length = X_train.shape[-1]
if y_train.dtype == object or isinstance(y_train[0], str):
    le = LabelEncoder()
    y_train = le.fit_transform(y_train)
    y_test = le.transform(y_test)

In [5]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train.reshape(X_train.shape[0], -1))
X_test_scaled = scaler.transform(X_test.reshape(X_test.shape[0], -1))


X_min = X_train_scaled.min(axis=0)
X_max = X_train_scaled.max(axis=0)

denom = (X_max - X_min)
denom[denom == 0] = 1   # avoid division by zero

X_train_norm = (X_train_scaled - X_min) / denom
X_test_norm  = (X_test_scaled  - X_min) / denom

# Optional: clip to [0,1] just in case
X_train_norm = np.clip(X_train_norm, 0, 1)
X_test_norm  = np.clip(X_test_norm, 0, 1)
X_train_tensor = torch.tensor(X_train_norm, dtype=torch.float32).to(device)
X_test_tensor = torch.tensor(X_test_norm, dtype=torch.float32).to(device)

In [6]:
y_train_tensor = torch.tensor(y_train, dtype=torch.long).to(device)
y_test_tensor = torch.tensor(y_test, dtype=torch.long).to(device)

train_data = TensorDataset(X_train_tensor, y_train_tensor)
test_data = TensorDataset(X_test_tensor, y_test_tensor)
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = DataLoader(test_data, batch_size=32, shuffle=False)

num_classes = len(np.unique(y_train))

In [7]:
# 1. Generate bipolar lookup table
def lookup_generate(dim: int, datatype: str, n_keys: int, device: torch.device):
    if datatype != 'bipolar':
        raise ValueError("Only 'bipolar' supported")
    tbl = torch.randint(0, 2, (n_keys, dim), device=device, dtype=torch.int8)
    return tbl * 2 - 1  # map {0,1} → {-1,+1}

# 2. Encode a batch of inputs into hypervectors
@torch.no_grad()
def encode_batch(X: torch.Tensor, position_table: torch.Tensor, grayscale_table: torch.Tensor):
    n_keys = grayscale_table.shape[0]
    X_normalized = ((X + 3) / 6) * (n_keys - 1)  # map [-3,3] → [0, n_keys-1]
    X_indices = X_normalized.round().clamp(0, n_keys - 1).long()  # indices in [0, n_keys-1]
    gray = grayscale_table[X_indices]            # (N, D_in, dim)
    pos  = position_table.unsqueeze(0)           # (1, D_in, dim)
    hv   = (pos * gray).sum(dim=1)               # (N, dim)
    return hv

# 3. Train associative memory by summing all encodings per class
def train_am(X_train, Y_train, position_table, grayscale_table, dim: int):
    H_train = encode_batch(X_train, position_table, grayscale_table).float()  # (N, dim)
    C = int(Y_train.max().item()) + 1
    am = torch.zeros((C, dim), device=X_train.device, dtype=torch.float32)
    am = am.index_add(0, Y_train, H_train)
    return am

# 4. Single-image prediction (returns class and query HV)
@torch.no_grad()
def predict_(am, img, position_table, grayscale_table):
    qhv = encode_batch(img.unsqueeze(0), position_table, grayscale_table).squeeze(0).float()
    sims = F.cosine_similarity(qhv.unsqueeze(0), am, dim=1)  # (C,)
    pred = int(sims.argmax().item())
    return pred, qhv

def predict(am, img, position_table, grayscale_table):
    pred, _ = predict_(am, img, position_table, grayscale_table)
    return pred

# 5. Test on full set
@torch.no_grad()
def test(am, X_test, Y_test, position_table, grayscale_table):
    H_test = encode_batch(X_test, position_table, grayscale_table).float()  # (N_test, dim)
    h_norm = H_test.norm(dim=1, keepdim=True)                              # (N,1)
    a_norm = am.norm(dim=1, keepdim=True).t()                              # (1,C)
    sims   = (H_test @ am.t()) / (h_norm * a_norm)                         # (N,C)
    preds  = sims.argmax(dim=1)                                            # (N,)
    acc    = (preds == Y_test).float().mean().item()
    print(f"Testing accuracy: {acc:.4f}")
    return acc

# 6. Load a saved model (AM + tables)
def loadmodel(fpath: str, device: torch.device = None):
    with open(fpath, 'rb') as f:
        am_np, pos_np, gray_np = pickle.load(f)
    am   = torch.from_numpy(am_np)
    pos  = torch.from_numpy(pos_np)
    gray = torch.from_numpy(gray_np)
    if device is not None:
        am, pos, gray = am.to(device), pos.to(device), gray.to(device)
    return am, pos, gray

# 7. Quantize the AM to a lower bit-width
def quantize(am: torch.Tensor, before_bw: int, after_bw: int) -> torch.Tensor:
    if before_bw <= after_bw:
        return am.clone()
    shift = before_bw - after_bw
    return torch.round(am.float() / (2 ** shift)).to(am.dtype)

# 8. Batched AM training
@torch.no_grad()
def train_am_batched(
    X_train: torch.Tensor,
    Y_train: torch.Tensor,
    position_table: torch.Tensor,
    grayscale_table: torch.Tensor,
    dim: int,
    batch_size: int = 128,
    device: torch.device = None
) -> torch.Tensor:
    N = X_train.shape[0]
    C = int(Y_train.max().item()) + 1
    am = torch.zeros(C, dim, device=device, dtype=torch.float32)
    for i in (range(0, N, batch_size)):
        xb = X_train[i : i + batch_size]
        yb = torch.as_tensor(Y_train[i : i + batch_size], device=device)  # <== ✅ fixed
        hb = encode_batch(xb, position_table, grayscale_table).float()
        am = am.index_add(0, yb, hb)
    return am

# 9. Test on a split (non-batched)
@torch.no_grad()
def test_split(am, X_split, Y_split, position_table, grayscale_table):
    Hs   = encode_batch(X_split, position_table, grayscale_table).float()  # (M, dim)
    sims = F.cosine_similarity(Hs.unsqueeze(1), am.unsqueeze(0), dim=2)   # (M, C)
    preds = sims.argmax(dim=1)                                            # (M,)
    return (preds == Y_split).float().mean().item()

# 10. Test on a split (batched)
@torch.no_grad()
def test_split_batched(
    am: torch.Tensor,
    X: torch.Tensor,
    Y: torch.Tensor,
    position_table: torch.Tensor,
    grayscale_table: torch.Tensor,
    encode_fn,
    batch_size: int = 128,
    device: torch.device = None
) -> float:
    correct, total = 0, 0
    for i in range(0, X.size(0), batch_size):
        xb = X[i : i + batch_size].to(device)
        yb = Y[i : i + batch_size].to(device)
        hb = encode_fn(xb, position_table, grayscale_table).float()
        sims  = F.cosine_similarity(hb.unsqueeze(1), am.unsqueeze(0), dim=2)
        preds = sims.argmax(dim=1)
        correct += (preds == yb).sum().item()
        total   += yb.size(0)
    return correct / total

In [9]:
try:
    hyperdims = np.mean(loadmat(f'../{dataset_name}_nHD.mat')[f'{dataset_name}_nHD'], 
                    axis=1, dtype=int)

except:
    hyperdims = range(5000, 15000, 2500)
print(hyperdims)

[ 5666  6333  7333  8666  9666 10666 12000 13000 13666 14666 16000]


In [10]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# n_rounds   = 20
n_splits = 20
split_size = len(test_data) // n_splits
# hyperdims = range(20000, 23000, 1000)
accuracies = np.zeros((len(hyperdims), n_splits))
n_class    = num_classes
q_bit      = 16
print(split_size)

6


In [11]:
X_train.shape, X_test.shape

((137, 3, 206), (138, 3, 206))

In [12]:
for i, D in enumerate(hyperdims):
    print(f"\n==> Hyperdimension: {D}")
    for split_idx in range(n_splits):
        # Dynamically get input dimension
        input_dim = X_train_tensor.shape[1] 
        n_keys = 64                   
        position_table  = lookup_generate(D, 'bipolar', input_dim, device=device)
        grayscale_table = lookup_generate(D, 'bipolar', n_keys, device=device)
        am = train_am_batched(
            X_train_tensor, y_train_tensor,
            position_table, grayscale_table,
            dim=D,
            batch_size=1,
            device=device
        )
        indices = list(range(len(X_test_tensor)))
        np.random.shuffle(indices)  # or random.shuffle(indices)
        am_q = quantize(am, before_bw=16, after_bw=q_bit)
        acc = test_split_batched(
            am_q,
            X_test_tensor,
            y_test_tensor,
            # X_test_tensor,
            # y_test_tensor,
            position_table,
            grayscale_table,
            encode_batch,  
            batch_size=10,
            device=device
        )
        accuracies[i, split_idx] = acc*100

    print("Accuracy average for 20 rounds:", accuracies[i].mean())

    # Free GPU memory
    del position_table, grayscale_table, am, am_q
    torch.cuda.empty_cache()



==> Hyperdimension: 5666
Accuracy average for 20 rounds: 83.18840579710145

==> Hyperdimension: 6333
Accuracy average for 20 rounds: 83.55072463768116

==> Hyperdimension: 7333
Accuracy average for 20 rounds: 83.22463768115942

==> Hyperdimension: 8666
Accuracy average for 20 rounds: 83.44202898550726

==> Hyperdimension: 9666
Accuracy average for 20 rounds: 84.27536231884059

==> Hyperdimension: 10666
Accuracy average for 20 rounds: 83.65942028985508

==> Hyperdimension: 12000
Accuracy average for 20 rounds: 83.8768115942029

==> Hyperdimension: 13000
Accuracy average for 20 rounds: 83.29710144927536

==> Hyperdimension: 13666
Accuracy average for 20 rounds: 83.51449275362319

==> Hyperdimension: 14666
Accuracy average for 20 rounds: 84.38405797101449

==> Hyperdimension: 16000
Accuracy average for 20 rounds: 83.91304347826085


In [13]:
np.mean(accuracies, axis=1)

array([83.1884058 , 83.55072464, 83.22463768, 83.44202899, 84.27536232,
       83.65942029, 83.87681159, 83.29710145, 83.51449275, 84.38405797,
       83.91304348])

In [17]:
savemat(f'{dataset_name}_VanillaHDC.mat', {f'{dataset_name}_VanillaHDC': accuracies})

In [18]:
np.std(accuracies, axis=1)

array([1.8130429 , 1.43287826, 1.28150284, 1.30182929, 0.94758673,
       1.2440786 , 1.02158494, 1.30585662, 1.31387423, 1.22279254,
       1.4051246 ])